CapstoneProject/CapstoneProject/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneProject.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        public ActionResult GoToCalendar()
        {
            return View();
        }
    }
}

CapstoneProject/CapstoneProject/Controllers/EventsController.cs
using CapstoneProject.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Routing;

namespace CapstoneProject.Controllers
{
    public class EventsController : Controller
    {


        public ActionResult SearchForEvents()
        {
            return View();
        }

        public async Task<ActionResult> ViewEvents(EventModel.SearchParams searchParams)
        {
            List<EventModel.Event> allEvents = new List<EventModel.Event>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://api.eventful.com");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                string url = "/json/events/search?...&keywords=fitness&location=" + searchParams.state + "&app_key=f82xVFHpZXDFfbck";
                var response = client.GetAsync(url).Result;
                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    EventModel.RootObject model = JsonConvert.DeserializeObject<EventModel.RootObject>(result);
                    foreach (EventModel.Event item in model.events.@event)
                    {
                        EventModel.Event events = new EventModel.Event();
                        events.latitude = item.latitude;
                        events.longitude = item.longitude;
                        events.city_name = item.city_name;
                        events.title = item.title;
                        events.start_time = item.start_time;
                        events.stop_time = item.stop_time;
                        events.venue_address = item.venue_address;                  
                        allEvents.Add(events);
                    }
                }
            }
            return View(allEvents);
        }
    }
}

CapstoneProject/CapstoneProject/Views/Events/SearchForEvents.cshtml
@model CapstoneProject.Models.EventModel.SearchParams
@{
    ViewBag.Title = "SearchForEvents";
}

@using (Html.BeginForm("ViewEvents", "Events"))
{
    <div style="margin-left: 35%;" >
        <h1 id="heading">Search For Events</h1>
        <br />
        <div class="form-group" style="font-size: 25px;">
            <h3>Type a state to search events.</h3>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.state, new { @class = "form-control", id = "searchInput" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="buttonNav" value="Search" />
            </div>
        </div>
    </div>
}

<script>
    function post() {
        var Search = $("#searchInput").val();
        $.ajax({
            type: "GET",
            url: "ViewEvents",
            coontentType: "application/json",
            data: {
                "Search": Search
            },
            dataType: "json",

            success: function (data) {
                console.log(data)
            },
            error: function (req, status, error) {
                console.log(req);
            }
        });
        return false;
    };

</script>


<style>
    #buttonNav
       {
           background-color: #4717F6;
           border-color: black;
           color: #E7DFDD;
           font-size: 30px;
           margin-top: 10px;
           margin-left: -30px;
           border-radius: 5px;             
       }
</style>







@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapstoneProject/CapstoneProject/Views/Events/ViewEvents.cshtml
@model IEnumerable<CapstoneProject.Models.EventModel.Event>
@using Newtonsoft.Json
@{
    ViewBag.Title = "ViewEvents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyCwr4my9cokU5JiXc41ODW41OOjBpHeMMg"
            type="text/javascript"></script>
</head>

<body>

    <p id="header">Events map </p>

    <p class="body">Click on pins to learn more about event. </p>
    <p class="body">@Html.ActionLink("Go to Google Calendar", "GoToCalendar", "Calendar", new { }, new { @class = "Search" })</p>

    <div id="map" style="width: 800px; height: 430px; display: block; margin: 0 auto"></div>
    <br />
    <script type="text/javascript">
        var data = @Html.Raw(Json.Encode(Model));

        var dataLength = data.length
        var locations = [];
        for (var e = 0; e < dataLength; e++)
        {
            
            var eventInfo = '<div id="content">' +
                   '<div id="siteNotice">' +
                   '</div>' +
                   '<h1 id="firstHeading" class="firstHeading"></h1>' +
                   '<div id="bodyContent">' +
                   '<h3>' + data[e].title + '</h3>' +
                   '<p>City: ' +  data[e].city_name + '</p>' +
                   '<p>Address: ' +  data[e].venue_address + '</p>' +              
                   '<p>Event Start Time: ' +  data[e].start_time + '</p>' +
                   '<p>Event End Time: ' +  data[e].stop_time + '</p>' + 
                   '</div>' +
                   '</div>';
            var eventObj = { eventInfo: eventInfo, lat: data[e].latitude, long: data[e].longitude}
            locations.push(eventObj);
        }


        var i = 0;

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: new google.maps.LatLng(data[0].latitude, data[0].longitude),
            mapTypeId: google.maps.MapTypeId.ROADMAP 
        });

        var infowindow = new google.maps.InfoWindow();

        var marker;

        for (i = 0; i < locations.length; i++) {

            marker = new google.maps.Marker({
                position: new google.maps.LatLng(data[i].latitude, data[i].longitude),
                map: map
            });

            google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                    infowindow.setContent(locations[i].eventInfo);
                    infowindow.open(map, marker);
                }
            })(marker, i));
        }
    </script>

<style>
    #header {
        text-align: center;
        font-size: 40px;
    }

    .body {
        text-align: center;
        font-size: 30px;
    }


</style>

</body>
</html>