CapstoneProject/CapstoneProject/Controllers/FriendsController.cs
using CapstoneProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CapstoneProject.Controllers
{
    public class FriendsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult FriendsHome()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
            {
                return RedirectToAction("RegisterAccessRequired", "ErrorMessages");
            }
        }
        public ActionResult SearchForFriends()
        {
            
            return View();
        }
        
        public ActionResult FriendAdded(FriendSearchModel search)
        {
            string currentUserId = User.Identity.GetUserId();
            string friend = search.addedFriend;

            var friendId = from f in db.Users
                           where f.Email == search.addedFriend
                           select f.Id;

            
            Friends friends = new Friends();
            friends.id = 0;
            friends.AdderName = currentUserId;
            friends.FriendName = friendId.FirstOrDefault();          
            db.Friends.Add(friends);
            db.SaveChanges();

            return View();
        }

        public ActionResult ViewAllUsers()
        {
            var allUsers = db.Users.ToList();
            return View(allUsers);
        }
       
        public ActionResult ViewFriendList()
        {

            return View();
        }

        public ActionResult ViewFriendWorkout()
        {
            return View();
        }
    }
}

CapstoneProject/CapstoneProject/Views/Friends/FriendAdded.cshtml
@{
    ViewBag.Title = "FriendAdded";
}

<div>
    <h2 id="header">Friend Added!</h2>  
     <img id="image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Check_mark_23x20_02.svg/1081px-Check_mark_23x20_02.svg.png" alt="Checkmark">
</div>

<style>
    #header {
        text-align: center;
    }
    #image {
        width: 350px;
        height: 300px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        padding: 30px;
        width: 400px;
        height: 400px;
    }

    .button {
        background-color: #4717F6;
        border-color: black;
        border: 2px solid #0E0B16;
        color: #E7DFDD;
        width: 350px;
        height: 50px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        font-size: 30px;
        text-align: center;
        border-radius: 5px;
    }

    a:hover {
        color: black;
    }
</style>

CapstoneProject/CapstoneProject/Views/Friends/FriendSearchResults.cshtml
@{
    ViewBag.Title = "FriendSearchResults";
}

<h2>Here's what we found...</h2>

CapstoneProject/CapstoneProject/Views/Friends/FriendsHome.cshtml
@{
    ViewBag.Title = "FriendsHome";
}


<body>

    <p><a class="button" href='@Url.Action("ViewAllUsers", "Friends")'>Add a friend &raquo;</a></p>

    <p><a class="button" href='@Url.Action("ViewFriendList", "Friends")'>View my friends &raquo;</a></p>

</body>

<style>
    .button {
        background-color: #4717F6;
        border-color: black;
        border: 2px solid #0E0B16;
        color: #E7DFDD;
        width: 450px;
        height: 50px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        font-size: 30px;
        text-align: center;
        border-radius: 5px;
        margin-top: 30px;

    }

    a:hover {
        color: white;
    }
</style>

CapstoneProject/CapstoneProject/Views/Friends/SearchForFriends.cshtml
@model CapstoneProject.Models.FriendSearchModel
@{
    ViewBag.Title = "SearchForFriends";
}

<h2 id="header">Type your friend's email to add!</h2>

@using (Html.BeginForm("FriendAdded", "Friends"))
{
    <fieldset>
        <div id="form">
            <div>
                @Html.TextBoxFor(m => m.addedFriend, new { @class = "form-control", id = "searchInput" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="buttonNav" value="Add Friend" />
            </div>
        </div>
    </fieldset>
}


<style>
    #header {
        text-align: center;
        font-size: 40px;
        margin-left: -10%;  
    }

    #form {
       margin-left: auto;
        margin-right: auto;
        margin-left: 32%;
        width: 400px;
    }

    .buttonNav {
        background-color: #4717F6;
        border-color: black;
        color: #E7DFDD;
        font-size: 30px;
        margin-top: 10px;
        margin-left: 24%;        
        border-radius: 5px;
    }
   a:hover {
        color: white;
    }
</style>

CapstoneProject/CapstoneProject/Views/Friends/ViewAllUsers.cshtml
@model IEnumerable<CapstoneProject.Models.ApplicationUser>
@{
    ViewBag.Title = "ViewAllUsers";
}

<h2 id="heading">Here's some possible friends...</h2>
<br />
<p id="paragraph">Copy their Email address and click "Add Friends"</p>
<br />
@foreach (CapstoneProject.Models.ApplicationUser users in Model)
{
    <div class="text_size">
        <table align="center">
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => users.FirstName) @Html.DisplayFor(modelItem => users.LastName) ---> @Html.DisplayFor(modelItem => users.Email)
                </th>
            </tr>
        </table>
    </div>
}

<a id="buttonNav" href='@Url.Action("SearchForFriends", "Friends")'>Add Friends &raquo;</a>

<style>
    #heading {
        font-size: 30px;
        text-align: center;
    }

    #paragraph {
        font-size: 20px;
        text-align: center;
    }

    .text_size {
        font-size: 20px;     
    }

     #buttonNav {
      background-color: #4717F6;
        border-color: black;
        border: 2px solid #0E0B16;
        color: #E7DFDD;
        width: 450px;
        height: 50px;
        display: block;
        margin-left: auto;
        margin-right: auto;
        font-size: 30px;
        text-align: center;
        border-radius: 5px;
        margin-top: 30px;
    }

</style>

CapstoneProject/CapstoneProject/Views/Friends/ViewFriendList.cshtml
@{
    ViewBag.Title = "ViewFriendList";
}

<h2>ViewFriendList</h2>

CapstoneProject/CapstoneProject/Views/Friends/ViewFriendWorkouts.cshtml
@{
    ViewBag.Title = "ViewFriendWorkouts";
}

<h2>ViewFriendWorkouts</h2>